#!/usr/bin/env ruby
# vim: set ft=rb

require 'pathname'
require_relative './lib/helpers.rb'

case ARGV[0]
when "current", "c", nil
  puts Problem.current.to_s
when "current-input", "ci"
  puts Problem.current.input_file
when "current-example", "ce"
  puts Problem.current.example_file
when "next", "n"
  puts Problem.next.to_s
when "repl", "r"
  Repl.run(ARGV[1..])
when "input", "i"
  Problem.current.download_input
when "day", "d", "create", "cr"
  Problem.next.create_file
when "example", "e"
  Problem.current.paste_example
else
  puts "Error: invalid argument #{ARGV.join(" ")}"
  puts "Usage -> helper (current|next|repl|create)"
end